### DISCUSSION TITLE
What is the right way to use backup feature?

### DISCUSSION THREAD

**Discussion by percy507** [rusqlite/rusqlite#1181] [Questions] [answered]
I am try to use backup feature to backup my database. 

But it seems backup function stuck the thread. And the value of backup progress always is `Progress { remaining: 0, pagecount: 0 }`.  This makes me very confused. Any hint will be grateful.

```toml
#cargo.toml
[package]
name = "learn-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.rusqlite]
version = "0.27.0"
features = ["bundled-sqlcipher-vendored-openssl", "backup", "hooks"]
```

```rs
use rusqlite::{backup, Connection, Result};
use std::path::Path;
use std::time::Duration;

fn main() -> Result<()> {
  let path = Path::new("../local.sqlite");
  let conn = Connection::open(&path)?;

  backup_db(&conn, path, |p| {
    println!("backup progress ==> {:?}", p);
  })?;

  println!("after backup");

  conn.execute(
    "CREATE TABLE IF NOT EXISTS table1 (
      id TEXT PRIMARY KEY, 
      text TEXT NOT NULL
    )",
    [],
  )?;
  conn.execute(
    "INSERT INTO table1 (id, text) 
    VALUES(strftime('%s', 'now'), strftime('%s', 'now'))",
    [],
  )?;

  Ok(())
}

fn backup_db<P: AsRef<Path>>(
  from: &Connection,
  db_path: P,
  progress: fn(backup::Progress),
) -> Result<()> {
  let mut to = Connection::open(db_path)?;
  let backup = backup::Backup::new(from, &mut to)?;
  backup.run_to_completion(1, Duration::from_millis(250), Some(progress))?;
  Ok(())
}
```

And...

> What is the right way to restore backup?🥺
