### ISSUE TITLE
Version 0.26.0 with bundled feature keeps recompiling dependencies

### ISSUE THREAD

**Issue by crumblingstatue** [rusqlite/rusqlite#1030]
```toml
[dependencies]
rusqlite.version = "0.26.0"
rusqlite.features = ["bundled"]
```

Every time we issue cargo run, the following dependencies are recompiled:
```
$ cargo r
   Compiling libsqlite3-sys v0.23.1
   Compiling rusqlite v0.26.0
   Compiling test2 v0.1.0 (/tmp/test2)
  ```
  
  This doesn't happen with version 0.25.0

Platform: Linux x86_64
