### ISSUE TITLE
libsqlite3-sys always recompiles on Windows when bundled feature is used

### ISSUE THREAD

**Issue by LunarLambda** [rusqlite/rusqlite#1331]
Cargo.toml:
```toml
[dependencies]
rusqlite = { version = "0.29.0", features = ["bundled"] }
```

`cargo build` takes about a minute flat for minute changes because it's recompiling/relinking libsqlite3-sys. (work machine with a very aggressive AV...)

A similar issue was fixed in https://github.com/rusqlite/rusqlite/pull/627 but doesn't seem to apply to the `bundled` feature.
I believe this can be fixed using the appropriate `cargo:rerun-if-changed` directives, but I only briefly glanced at the build script.
