### ISSUE TITLE
How to build on aarch64-apple-darwin?

### ISSUE THREAD

**Issue by andrejohansson** [rusqlite/rusqlite#1615]
What is needed to build this crate on aarch64-apple-darwin? 

This is my cargo.toml

```toml
rusqlite =  { version = "0.31.0", features = ["bundled"]}
```

Here is my gitlab ci job

```yaml
apple-arm:
  stage: build
  image: joseluisq/rust-linux-darwin-builder:1.83.0
  script:
    - apt update
    - apt install -y protobuf-compiler musl-tools pkg-config zip git
    - CC=o64-clang CXX=o64-clang++ cargo build --release --target aarch64-apple-darwin
```

I am using the build image from: https://github.com/joseluisq/rust-linux-darwin-builder and I get the following error:

```shell
2024-12-13T11:02:52.182353Z 01E   = note: ld: in /builds/andre.johansson/pj-cli/target/aarch64-apple-darwin/release/deps/liblibsqlite3_sys-29747f8517ec528f.rlib(c877a2978823c39d-sqlite3.o), archive member 'c877a2978823c39d-sqlite3.o' with length 2124888 is not mach-o or llvm bitcode for architecture arm64
2024-12-13T11:02:52.182357Z 01E           clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
