### ISSUE TITLE
Cannot load extensions when compiled with musl

### ISSUE THREAD

**Issue by phinjensen** [rusqlite/rusqlite#990]
I'm not sure if this is really a bug or if I am missing something, but when I compile for musl and try to load an extension, I get the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("Dynamic loading not supported"))', src/main.rs:10:14
```

main.rs:

```rust
use rusqlite::{Connection, LoadExtensionGuard};
use std::path::Path;

fn main() {
    let mut conn = Connection::open_in_memory().unwrap();

    {
        let _guard = LoadExtensionGuard::new(&conn).unwrap();
        conn.load_extension(Path::new("/usr/lib/sqlite3/pcre.so"), None)
            .unwrap();
    }
}
```

And Cargo.toml, which does have loading extensions and bundled sqlite included:

```toml
[package]
name = "rusqlite_test"
version = "0.1.0"
authors = ["Phineas Jensen <phin@zayda.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.25.0", features = ["load_extension", "bundled"] }
```

Is this a bug with rusqlite or sqlite or musl, or simply an unsupported feature? Does anyone know of any workarounds for it?
