### ISSUE TITLE
the trait bound `OffsetDateTime: FromSql` is not satisfied (the trait `FromSql` is not implemented for `OffsetDateTime`)

### ISSUE THREAD

**Issue by fossdd** [rusqlite/rusqlite#997]
I've got the following error by using `FromSql` and `ToSql` with `time::OffsetDateTime`.

```
error[E0277]: the trait bound `OffsetDateTime: FromSql` is not satisfied
   --> src/main.rs:251:35
    |
251 |                 date_created: row.get(10)?,
    |                                   ^^^ the trait `FromSql` is not implemented for `OffsetDateTime`
```

Of course, I loaded all items that are required (also like https://github.com/rusqlite/rusqlite/issues/240)

```rust
use rusqlite::{params, Connection, Result};
use rusqlite::types::*;

use time::OffsetDateTime;
```

I am using the latest git version of both packages and activated the `time` feature for rusqlite:

```toml
time = { git = "https://github.com/time-rs/time.git" }
rusqlite = { git = "https://github.com/rusqlite/rusqlite.git", features = ["time"] }
```

So, what  am I doing wrong, or is it a error by rusqlite/time?
